export const blogData = [
  {
    id: 1,
    image: "https://i.ibb.co/jhmVvDY/Rectangle-24.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 2,
    image: "https://i.ibb.co/ssDwKfc/Rectangle-24-1.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 3,
    image: "https://i.ibb.co/YPrTbDx/Rectangle-24-2.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 4,
    image: "https://i.ibb.co/TbLLygV/Rectangle-24-3.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 5,
    image: "https://i.ibb.co/f02SPnw/Rectangle-24-5.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 6,
    image: "https://i.ibb.co/T2DPwJg/Rectangle-24-4.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 7,
    image: "https://i.ibb.co/L1F2Ysp/Rectangle-24-6.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 7,
    image: "https://i.ibb.co/yXw6nf7/Rectangle-24-7.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
  {
    id: 8,
    image: "https://i.ibb.co/tcDm9vs/Rectangle-24-8.png",
    title: "Time Mastery in the Digital Age",
    date: "06 Sep, 2023",
    time: "2 min",
    text: "This blog explores practical strategies for efficiently managing your time in today's fast-paced digital era.",
  },
];
