export const coFounderCardData = [
  {
    id: 1,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 2,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 3,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 4,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 5,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 6,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 7,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 8,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 9,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 10,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 11,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 12,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 13,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 14,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 15,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
  {
    id: 16,
    name: "Tom Blaisdell",
    degi: "Software Engineer, Project Manger",
    experience: "6 Years of Experience in Business Development ",
    image: "/1.jpg",
  },
];
