export const startupBlogData = [
  {
    id: 1,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 2,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 3,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 4,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 5,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 6,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 7,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 8,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 9,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 10,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 11,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 12,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
];

export const startupTeamTabData = [
  {
    id: 1,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Paul Scanlan",
    desecration: "Co-Founder & CEO",
    text: "Emmy winning serial entrepreneur, Cofounder/President MobiTV, 2011 Forbes 'Names You Need to Know', Adjunct Lecturer of Entrepreneurship at NU Kellogg.",
  },
  {
    id: 2,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Paul Scanlan",
    desecration: "Co-Founder & CEO",
    text: "Emmy winning serial entrepreneur, Cofounder/President MobiTV, 2011 Forbes 'Names You Need to Know', Adjunct Lecturer of Entrepreneurship at NU Kellogg.",
  },
  {
    id: 3,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Paul Scanlan",
    desecration: "Co-Founder & CEO",
    text: "Emmy winning serial entrepreneur, Cofounder/President MobiTV, 2011 Forbes 'Names You Need to Know', Adjunct Lecturer of Entrepreneurship at NU Kellogg.",
  },
  {
    id: 4,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Paul Scanlan",
    desecration: "Co-Founder & CEO",
    text: "Emmy winning serial entrepreneur, Cofounder/President MobiTV, 2011 Forbes 'Names You Need to Know', Adjunct Lecturer of Entrepreneurship at NU Kellogg.",
  },
  {
    id: 5,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Paul Scanlan",
    desecration: "Co-Founder & CEO",
    text: "Emmy winning serial entrepreneur, Cofounder/President MobiTV, 2011 Forbes 'Names You Need to Know', Adjunct Lecturer of Entrepreneurship at NU Kellogg.",
  },
  {
    id: 6,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Paul Scanlan",
    desecration: "Co-Founder & CEO",
    text: "Emmy winning serial entrepreneur, Cofounder/President MobiTV, 2011 Forbes 'Names You Need to Know', Adjunct Lecturer of Entrepreneurship at NU Kellogg.",
  },
];

export const discussionContentData = [
  {
    id: 1,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Mark Deyal",
    time: "3 years ago",
    text: "When is this investment going to finish, close, or finalize? Do you have an idea on a month in 2024 for closing time",
  },
  {
    id: 2,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Mark Deyal",
    time: "3 years ago",
    text: "When is this investment going to finish, close, or finalize? Do you have an idea on a month in 2024 for closing time",
  },
  {
    id: 3,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Mark Deyal",
    time: "3 years ago",
    text: "When is this investment going to finish, close, or finalize? Do you have an idea on a month in 2024 for closing time",
  },
  {
    id: 4,
    image: "https://i.ibb.co/9qWJdkH/6.jpg",
    name: "Mark Deyal",
    time: "3 years ago",
    text: "When is this investment going to finish, close, or finalize? Do you have an idea on a month in 2024 for closing time",
  },
];
