export const startupData = [
  {
    id: 1,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 2,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 3,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 4,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 5,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 6,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 7,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 8,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 9,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 10,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 11,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
  {
    id: 12,
    image: "https://i.ibb.co/47YK1NH/startup-3267505-1280.jpg",
    title: "INVEST IN KLIKEN",
    tagline: "GPT AI-powered Digital Marketing Platform for Small Businesses",
    description:
      " Music Platform helping independent musicians get booked, earn income and grow their fanbases",
    facilities: ["Venture Backed", "Advertisement", "High Revenue"],
    investorAmount: "184,050",
    totalInvestors: 74,
    companyValuations: "10.00M",
    profile: "https://i.ibb.co/9qWJdkH/6.jpg",
  },
];
